# Generated by Django 4.2.30 on 2026-04-25 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Bo'lim nomi")),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Jadval nomi')),
                ('start_time', models.TimeField(verbose_name='Ish boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Ish tugash vaqti')),
                ('late_tolerance_minutes', models.IntegerField(default=15, verbose_name='Kechikish chegarasi (daqiqa)')),
                ('overtime_threshold_minutes', models.IntegerField(default=30, verbose_name="Qo'shimcha ish chegarasi (daqiqa)")),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ish jadvali',
                'verbose_name_plural': 'Ish jadvallari',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Lavozim nomi')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Asosiy maosh')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='core.department', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': 'Lavozim',
                'verbose_name_plural': 'Lavozimlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Otasining ismi')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='Xodim ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('gender', models.CharField(choices=[('M', 'Erkak'), ('F', 'Ayol')], default='M', max_length=1, verbose_name='Jinsi')),
                ('hire_date', models.DateField(verbose_name='Ishga qabul sanasi')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Maosh')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Soatlik stavka')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol'), ('on_leave', "Ta'tilda")], default='active', max_length=20, verbose_name='Holat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.department', verbose_name="Bo'lim")),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.position', verbose_name='Lavozim')),
                ('work_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workschedule', verbose_name='Ish jadvali')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyWorkDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')], verbose_name='Hafta kuni')),
                ('is_working', models.BooleanField(default=True, verbose_name='Ish kuni')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_days', to='core.workschedule')),
            ],
            options={
                'ordering': ['day_of_week'],
                'unique_together': {('schedule', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Oy')),
                ('year', models.IntegerField(verbose_name='Yil')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Asosiy maosh')),
                ('working_days', models.IntegerField(default=0, verbose_name='Ish kunlari')),
                ('present_days', models.IntegerField(default=0, verbose_name='Kelgan kunlar')),
                ('absent_days', models.IntegerField(default=0, verbose_name='Kelmagan kunlar')),
                ('late_count', models.IntegerField(default=0, verbose_name='Kechikishlar soni')),
                ('late_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kechikish uchun ayirish')),
                ('early_leave_count', models.IntegerField(default=0, verbose_name='Erta ketishlar soni')),
                ('early_leave_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Erta ketish uchun ayirish')),
                ('absence_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kelmagan kun uchun ayirish')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name="Qo'shimcha ish soatlari")),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Qo'shimcha ish haqi")),
                ('total_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami ayirish')),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami maosh')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('calculated', 'Hisoblangan'), ('paid', "To'langan")], default='draft', max_length=20, verbose_name='Holat')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='core.employee', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Ish haqi',
                'verbose_name_plural': 'Ish haqilari',
                'ordering': ['-year', '-month', 'employee__last_name'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='Kelish vaqti')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Ketish vaqti')),
                ('status', models.CharField(choices=[('present', 'Vaqtida keldi'), ('late', 'Kechikdi'), ('absent', 'Kelmadi'), ('day_off', 'Dam olish kuni'), ('holiday', 'Bayram kuni'), ('incomplete', "To'liq emas"), ('overtime', "Qo'shimcha ish")], default='present', max_length=20, verbose_name='Holat')),
                ('late_minutes', models.IntegerField(default=0, verbose_name='Kechikish (daqiqa)')),
                ('early_leave_minutes', models.IntegerField(default=0, verbose_name='Erta ketish (daqiqa)')),
                ('overtime_minutes', models.IntegerField(default=0, verbose_name="Qo'shimcha ish (daqiqa)")),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.employee', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomat',
                'ordering': ['-date', 'employee__last_name'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
